# Generated by Django 5.0.3 on 2024-04-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=30)),
                ('service_description', models.TextField()),
                ('min_price', models.FloatField()),
                ('number_of_people', models.CharField(max_length=20)),
                ('big_photo', models.ImageField(upload_to='services')),
                ('little_photo', models.ImageField(upload_to='services')),
            ],
        ),
    ]
