# Generated by Django 5.0.3 on 2024-04-03 06:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('event_sponsor', models.CharField(max_length=255)),
                ('event_description', models.TextField()),
                ('event_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('event_count_participants', models.PositiveIntegerField(default=0)),
                ('event_tickets', models.PositiveIntegerField()),
                ('event_sold_tickets', models.PositiveIntegerField(default=0)),
                ('event_sold_out', models.BooleanField(default=False)),
                ('ticket_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('event_image', models.ImageField(default='events_images/defaulteventlogo.jpg', upload_to='events_images/')),
                ('venue', models.CharField(default='Online', max_length=255)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'event')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='joined_events', through='events.Participant', to=settings.AUTH_USER_MODEL),
        ),
    ]
